name: automated Python package

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '5 2 * * TUE,FRI' #runs at 2:05 UTC = 04:05 local (AMS) every Tuesday and Friday

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  numpy pandas cbsodata seaborn matplotlib
      - name: excecute py script
        run: |
          python Overledenen.py
          
      - name: Update graphs
        run: |
          git config --global user.name 'heesters'
          git config --global user.email 'heesters@users.noreply.github.com'
          git commit -am "Update graphs"
          git push
